name: Hex

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-22.04
    container:
      image: erlang:26
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup rebar3 hex
        run: |
          mkdir -p ~/.config/rebar3/
          echo "{plugins, [rebar3_hex]}." > ~/.config/rebar3/rebar.config

      - name: Publish to hex.pm
        run: rebar3 hex publish --repo hexpm --yes || head rebar3.crashdump
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
